version: '3'

services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    restart: always
    networks:
      - app-tier

#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    links:
#      - db
#    ports:
#      - 8085:80
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_HOST: db
#      PMA_PORT: 3306
#    networks:
#      - app-tier
  
  web:
    build:
      context: ./APIServer
    container_name: web
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./APIServer:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - app-tier
  
  client:
    build:
      context: ./Client
    container_name: client
    volumes:
      - ./Client:/app
      - ./Client/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: ["/bin/sh", "-c", "npm install && npm run dev -- --host"]  # npm install 후 Vite 서버 실행
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-tier

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - web
      - client
    restart: always
    networks:
      - app-tier

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-tier

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - app-tier

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - app-tier

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/tmp:/data/
    networks:
      - app-tier
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug

volumes:
  mysql_data:

networks:
  app-tier:
    driver: bridge