version: '3'

services:
  
  web:
    build:
      context: ./APIServer
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./APIServer:/app
    ports:
      - "8000:8000"
    networks:
      - app-tier
  
  client:
    build:
      context: ./Client
    container_name: client
    volumes:
      - ./Client:/app
      - ./Client/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: ["/bin/sh", "-c", "npm install && npm run dev -- --host"]  # npm install 후 Vite 서버 실행
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-tier

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - web
      - client
    restart: always
    networks:
      - app-tier

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-tier

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - app-tier

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - app-tier

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/tmp:/data/
    networks:
      - app-tier
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug


networks:
  app-tier:
    driver: bridge