global:
  scrape_interval: 5m  # 데이터 수집 주기를 5분으로 설정
  evaluation_interval: 5m  # 평가 주기도 5분으로 설정

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus:9090']
    scrape_timeout: 1m  # 스크랩 최대 대기 시간을 1분으로 설정

  - job_name: 'node-data'
    static_configs:
      - targets: [ 'node_exporter:9100' ]
    scrape_timeout: 1m  # 스크랩 최대 대기 시간을 1분으로 설정

  # GPU 서버 1
  - job_name: 'gpu-server-1'
    static_configs:
      - targets: ['192.168.122.104:9400']
    scrape_timeout: 1m  # 스크랩 최대 대기 시간을 1분으로 설정

  # GPU 서버 2
  - job_name: 'gpu-server-2'
    static_configs:
      - targets: ['192.168.122.105:9400']
    scrape_timeout: 1m  # 스크랩 최대 대기 시간을 1분으로 설정
