global:
  scrape_interval: 1m
  evaluation_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus:9090']
    scrape_timeout: 30s

  - job_name: 'node-data'
    static_configs:
      - targets: [ 'node_exporter:9100' ]
    scrape_timeout: 30s

  # GPU 서버 1
  - job_name: 'gpu-server-1'
    static_configs:
      - targets: ['117.16.196.144:9400']
    scrape_timeout: 1m
    tls_config:
      insecure_skip_verify: true

  # GPU 서버 2
  - job_name: 'gpu-server-2'
    static_configs:
      - targets: ['192.168.122.105:9400']
    scrape_timeout: 1m
    tls_config:
      insecure_skip_verify: true
